Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2020-09, with the labels that each got.

#654 Move files to /etc, /var/lib or /var/run dirs
  docs/content/en/docs/configuration/template.md
  pkg/common/ingress/controller/launch.go
  pkg/common/ingress/types.go
  pkg/common/net/ssl/ssl.go
  pkg/controller/controller.go
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/annotations/updater.go
  pkg/haproxy/config.go
  pkg/haproxy/instance.go
  pkg/haproxy/instance_test.go
  rootfs/Dockerfile
  rootfs/etc/haproxy/modsecurity/spoe-modsecurity-v07.tmpl
  rootfs/etc/lua/auth-request.lua
  rootfs/etc/lua/send-response.lua
  rootfs/etc/lua/services.lua
  rootfs/etc/templates/haproxy/haproxy.tmpl
  rootfs/etc/templates/map/map.tmpl
  rootfs/etc/templates/modsecurity/modsecurity.tmpl
  rootfs/haproxy-reload.sh
  rootfs/start.sh
Labels: v0.11

#658 Add wait-before-update command-line option
  docs/content/en/docs/configuration/command-line.md
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/controller/cache.go
  pkg/controller/controller.go
Labels: v0.11

#659 Update to go1.14.8
  .travis.yml
Labels: v0.12

#660 Update to client-go v0.19.0
  go.mod
  go.sum
Labels: v0.12

#661 Update to haproxy 2.2.3
  rootfs/Dockerfile
Labels: v0.12

#662 Add path-type-order global config
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/annotations/global_test.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/types/global.go
  pkg/haproxy/config.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
Labels: v0.12

#667 Add better handling for cookie affinity with preserve option: add 'session-cookie-preserve' and 'session-cookie-value-strategy' options
  docs/content/en/docs/configuration/command-line.md
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/dynupdate.go
  pkg/haproxy/dynupdate_test.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/backend.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.12

#663 Add abstract per path config reader
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/mapper.go
  pkg/converters/ingress/annotations/mapper_test.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/backend.go
  pkg/haproxy/types/backend_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.12

#668 Fix rewrite target match
  pkg/haproxy/instance_test.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.10, v0.11, v0.12

#666 WIP: Add option to run an external haproxy instance
  docs/content/en/docs/configuration/command-line.md
  docs/content/en/docs/configuration/keys.md
  docs/content/en/docs/examples/external-haproxy.md
  docs/content/en/docs/examples/external-haproxy/daemonset-patch.yaml
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/controller/controller.go
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/annotations/global_test.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/types/global.go
  pkg/converters/ingress/types/options.go
  pkg/haproxy/dynupdate.go
  pkg/haproxy/instance.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/global.go
  pkg/haproxy/types/types.go
  pkg/haproxy/utils/utils.go
  pkg/haproxy/utils/utils_test.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
  rootfs/haproxy-reload.sh
  rootfs/start.sh
Labels: v0.12
