Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2020-05, with the labels that each got.

#564 Follow gofmt convention
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/mapper_test.go
Labels: v0.11

#563 Move listers and informers to the new controller
  pkg/common/ingress/controller/backend_ssl.go
  pkg/common/ingress/controller/backend_ssl_test.go
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/listers.go
  pkg/common/ingress/controller/status.go
  pkg/common/ingress/controller/status_test.go
  pkg/common/ingress/store/main.go
  pkg/common/ingress/types.go
  pkg/controller/cache.go
  pkg/controller/controller.go
  pkg/controller/leaderelection.go
  pkg/controller/listers.go
  pkg/utils/queue.go
  pkg/utils/queue_test.go
Labels: v0.11

#570 Server-alias doesn't not work on http:80 => 0.7.2 to 0.8.3 #565
  pkg/haproxy/config.go
Labels: v0.10, v0.11, v0.8, v0.9

#576 Add check interval on tcp service
  docs/content/en/docs/configuration/command-line.md
  pkg/converters/configmap/tcpservices.go
  pkg/converters/configmap/tcpservices_test.go
Labels: v0.10, v0.11

#577 Add use-forwarded-proto config key
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/types/global.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/haproxy/template/haproxy.tmpl
Labels: v0.10, v0.11

#578 Fix permission using watch-namespace
  pkg/common/ingress/controller/launch.go
Labels: v0.10, v0.11

#579 Fix watch-namespace option
  pkg/controller/controller.go
  pkg/controller/listers.go
Labels: v0.11

#575 Add headers config key
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/backend.go
  pkg/haproxy/types/types.go
  rootfs/etc/haproxy/template/haproxy.tmpl
Labels: v0.11

#588 Allow overriding CPU Map
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/annotations/global_test.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/types/global.go
Labels: v0.10, v0.11

#589 TCP Services : SSL : Optionally Verify Client
  docs/content/en/docs/configuration/command-line.md
  go.mod
  pkg/converters/configmap/tcpservices.go
  pkg/converters/configmap/tcpservices_test.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/haproxy/template/haproxy.tmpl
Labels: v0.10, v0.11
