Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2020-08, with the labels that each got.

#617 Host scope tls-alpn and ssl-options
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/annotations/host.go
  pkg/converters/ingress/annotations/host_test.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/types/annotations.go
  pkg/converters/ingress/types/global.go
  pkg/haproxy/config.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/haproxy/template/haproxy.tmpl
Labels: v0.11

#633 Add service event handler
  pkg/common/ingress/controller/listers.go
Labels: v0.10, v0.8, v0.9

#634 Configure default crt on ingress parsing phase
  pkg/controller/controller.go
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/converters/ingress/types/options.go
  pkg/haproxy/config.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
Labels: v0.10, v0.11, v0.8, v0.9

#637 Partial build of backend maps
  pkg/haproxy/config.go
Labels: v0.11

#638 Update to client-go v0.18.6
  go.mod
  go.sum
  pkg/common/ingress/controller/launch.go
  pkg/common/ingress/controller/status.go
  pkg/common/k8s/main.go
  pkg/controller/cache.go
Labels: v0.11

#640 Update to go1.13.15
  .travis.yml
  pkg/utils/queue_test.go
Labels: v0.11

#641 Add support to multiple match types
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/global_test.go
  pkg/converters/ingress/annotations/mapper.go
  pkg/converters/ingress/annotations/mapper_test.go
  pkg/converters/ingress/annotations/updater_test.go
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/config.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/backend.go
  pkg/haproxy/types/backend_test.go
  pkg/haproxy/types/frontend.go
  pkg/haproxy/types/frontend_test.go
  pkg/haproxy/types/host.go
  pkg/haproxy/types/host_test.go
  pkg/haproxy/types/maps.go
  pkg/haproxy/types/maps_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/haproxy/template/haproxy.tmpl
Labels: v0.11

#646 Add hostname and backend tracking on addIngress
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/converters/ingress/tracker/tracker.go
  pkg/converters/ingress/tracker/tracker_test.go
  pkg/converters/types/interfaces.go
Labels: v0.11

#644 Improve backend shrinking
  pkg/haproxy/types/backends.go
Labels: v0.11

#653 Fix tracking and partial parsing of spec.backend
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/host.go
  pkg/haproxy/types/types.go
Labels: v0.11
