Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2020-11, with the labels that each got.

#683 Fix line too long on backend parsing
  pkg/haproxy/instance_test.go
  pkg/haproxy/template/funcmap.go
  pkg/haproxy/types/backend.go
  pkg/haproxy/types/backend_test.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.10, v0.11, v0.12

#688 Fix basic auth backend tracking
  pkg/converters/ingress/annotations/backend.go
Labels: v0.11, v0.12

#695 Allow signer to work with wildcard dns certs
  pkg/acme/signer.go
  pkg/acme/signer_test.go
Labels: v0.10, v0.11, v0.12, v0.9

#689 Improve certificate validation of acme signer
  pkg/acme/signer.go
  pkg/acme/signer_test.go
  pkg/controller/cache.go
Labels: v0.11, v0.12

#692 Add worker-max-reloads config option
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/types/global.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.12

#694 Add ingress class support
  docs/content/en/docs/configuration/command-line.md
  docs/content/en/docs/configuration/keys.md
  docs/content/en/docs/getting-started/_index.md
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/common/ingress/controller/status.go
  pkg/controller/cache.go
  pkg/controller/controller.go
  pkg/controller/listers.go
  pkg/converters/helper_test/cachemock.go
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/converters/ingress/tracker/tracker.go
  pkg/converters/ingress/tracker/tracker_test.go
  pkg/converters/types/interfaces.go
Labels: v0.12
