Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2021-06, with the labels that each got.

#775 Add Gateway API support (part 1)
  docs/content/en/docs/configuration/command-line.md
  docs/content/en/docs/configuration/gateway-api.md
  docs/content/en/docs/configuration/keys.md
  docs/content/en/docs/configuration/template.md
  go.mod
  go.sum
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/controller/cache.go
  pkg/controller/controller.go
  pkg/controller/listers.go
  pkg/converters/configmap/tcpservices.go
  pkg/converters/configmap/tcpservices_test.go
  pkg/converters/converters.go
  pkg/converters/gateway/gateway.go
  pkg/converters/gateway/gateway_test.go
  pkg/converters/helper_test/cachemock.go
  pkg/converters/helper_test/k8sobjects.go
  pkg/converters/helper_test/marshal.go
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/annotations/updater_test.go
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/converters/ingress/utils/utils.go
  pkg/converters/ingress/utils/utils_test.go
  pkg/converters/tracker/tracker.go
  pkg/converters/tracker/tracker_test.go
  pkg/converters/types/interfaces.go
  pkg/converters/types/options.go
  pkg/converters/utils/lbweight.go
  pkg/converters/utils/lbweight_test.go
  pkg/haproxy/types/host.go
  pkg/haproxy/types/host_test.go
  pkg/haproxy/types/types.go
  pkg/types/client.go
  pkg/types/helper_test/loggermock.go
Labels: v0.13

#784 Allow more than 64k outgoing conn with source addr
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/dynupdate.go
  pkg/haproxy/instance.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/backend.go
  pkg/haproxy/types/backend_test.go
  pkg/haproxy/types/backends.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.13

#791 Fix domain validation on secure backend keys
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
Labels: v0.11, v0.12, v0.13

#789 Add option to disable API server warnings
  docs/content/en/docs/configuration/command-line.md
  pkg/common/ingress/controller/launch.go
Labels: v0.12, v0.13

#793 Add ssl-always-add-https config key
  docs/content/en/docs/configuration/keys.md
  pkg/converters/gateway/gateway.go
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/annotations/updater_test.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/config.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/backend.go
  pkg/haproxy/types/host.go
  pkg/haproxy/types/types.go
Labels: v0.12, v0.13

#794 Add option to copy client method to auth-url
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  rootfs/etc/lua/auth-request.lua
Labels: v0.13

#795 Add dynamic update for cross namespace reading
  docs/content/en/docs/configuration/command-line.md
  docs/content/en/docs/configuration/keys.md
  pkg/common/ingress/controller/controller.go
  pkg/controller/cache.go
  pkg/controller/controller.go
  pkg/converters/configmap/tcpservices.go
  pkg/converters/gateway/gateway.go
  pkg/converters/helper_test/cachemock.go
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/annotations/global_test.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/annotations/updater_test.go
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/converters/ingress/types/global.go
  pkg/converters/ingress/utils/utils.go
  pkg/converters/ingress/utils/utils_test.go
  pkg/converters/types/interfaces.go
  pkg/converters/types/options.go
Labels: v0.13

#797 Allow a list of origins in cors-allow-origin config
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/validator.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.13

#796 Use the port name on DNS resolver template
  pkg/converters/ingress/ingress.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.10, v0.11, v0.12, v0.13

#799 Fix reading of tls secret without crt or key
  pkg/controller/cache.go
Labels: v0.10, v0.11, v0.12, v0.13

#802 Fix backend match if no ingress use host match
  pkg/haproxy/instance_test.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.12, v0.13, v0.14

#801 Stable IDs for consistent-hash load balancing
  docs/content/en/docs/configuration/command-line.md
  docs/content/en/docs/configuration/keys.md
  pkg/converters/helper_test/marshal.go
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.13, v0.14

#804 Ensure that configured global ConfigMap exists
  pkg/common/ingress/controller/launch.go
Labels: v0.10, v0.11, v0.12, v0.13, v0.14
