Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2021-08, with the labels that each got.

#833 Gateway API: when using v1alpha1, certificateRef.group now accepts "core"
  pkg/converters/gateway/gateway.go
  pkg/converters/gateway/gateway_test.go
Labels: v0.13, v0.14

#827 Add close-sessions-duration config key
  docs/content/en/docs/configuration/command-line.md
  docs/content/en/docs/configuration/keys.md
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/controller/controller.go
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/annotations/global_test.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/types/global.go
  pkg/converters/types/options.go
  pkg/haproxy/connections.go
  pkg/haproxy/dynupdate.go
  pkg/haproxy/dynupdate_test.go
  pkg/haproxy/instance.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.14

#828 Fix set ssl cert end-of-command
  pkg/haproxy/dynupdate.go
  pkg/haproxy/dynupdate_test.go
  pkg/haproxy/socket/socket.go
  pkg/haproxy/socket/socket_test.go
Labels: v0.14

#829 Fix dynamic update of frontend crt
  pkg/haproxy/types/host.go
Labels: v0.13, v0.14

#835 Fix change notification of backend shard
  pkg/haproxy/dynupdate.go
  pkg/haproxy/types/backends.go
Labels: v0.11, v0.12, v0.13, v0.14

#826 Added docs on adding ClusterIP service for ModSecurity and removing NodeSelector
  docs/content/en/docs/examples/modsecurity.md
  docs/static/resources/modsecurity-deployment-auditlog-sidecar.yaml
  docs/static/resources/modsecurity-deployment.yaml
Labels: v0.13, v0.14

#837 docs: add a faq
  docs/content/en/docs/faq/_index.md
Labels: v0.13, v0.14

#836 Add arm64 build
  .github/workflows/image.yaml
Labels: v0.13, v0.14

#846 Feature/allowlist behind reverse proxy
  docs/content/en/docs/configuration/keys.md
  go.mod
  go.sum
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.13, v0.14

#841 docs: add modsec resource limits to controls V2 memory consumption
  docs/content/en/docs/examples/modsecurity.md
  docs/static/resources/modsecurity-deployment-auditlog-sidecar.yaml
  docs/static/resources/modsecurity-deployment.yaml
Labels: v0.13, v0.14

#843 Always deny requests if oauth is misconfigured
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.10, v0.11, v0.12

#847 Fix ingress update to an existing backend
  pkg/converters/ingress/ingress.go
Labels: v0.11, v0.12, v0.13, v0.14

#842 Fix endpoint update of configmap based tcp services
  pkg/converters/converters.go
Labels: v0.13, v0.14

#844 Fix config parsing on misconfigured auth external
  pkg/haproxy/instance_test.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.13, v0.14

#845 Fix validation if ca is used with crt and key
  pkg/common/net/ssl/ssl.go
Labels: v0.13, v0.14
