Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2021-07, with the labels that each got.

#809 Update auth-request.lua script
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/haproxy/instance_test.go
  rootfs/etc/lua/auth-request.lua
Labels: v0.13, v0.14

#810 Reload haproxy if a backend server cannot be found
  pkg/haproxy/dynupdate.go
  pkg/haproxy/dynupdate_test.go
Labels: v0.12, v0.13, v0.14

#811 Add log of reload error on every reconciliation
  pkg/haproxy/instance.go
Labels: v0.13, v0.14

#806 docs: Add all command-line options to list.
  docs/content/en/docs/configuration/command-line.md
Labels: v0.12, v0.13, v0.14

#816 Add disable-external-name commnand-line option
  docs/content/en/docs/configuration/command-line.md
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/controller/cache.go
  pkg/converters/helper_test/cachemock.go
  pkg/converters/types/interfaces.go
  pkg/converters/utils/services.go
  pkg/converters/utils/services_test.go
Labels: v0.10, v0.11, v0.12, v0.13, v0.14

#815 Add reload interval command-line option
  docs/content/en/docs/configuration/command-line.md
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/controller/controller.go
  pkg/haproxy/instance.go
Labels: v0.13, v0.14

#818 Fix auth-url parsing if hostname misses a dot
  pkg/converters/ingress/utils/utils.go
  pkg/converters/ingress/utils/utils_test.go
Labels: v0.13, v0.14

#819 Always deny requests of failed auth configurations
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.13, v0.14

#814 Updates to the help output of command-line options
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/controller/controller.go
  pkg/controller/listers.go
Labels: v0.13, v0.14

#820 Add disable-config-keywords command-line options
  docs/content/en/docs/configuration/command-line.md
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/controller/controller.go
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/types/options.go
Labels: v0.10, v0.11, v0.12, v0.13, v0.14

#821 Change nbthread to use all CPUs by default
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/defaults.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.13, v0.14

#824 Option to use client and master socket in keep alive mode
  pkg/haproxy/dynupdate.go
  pkg/haproxy/dynupdate_test.go
  pkg/haproxy/instance.go
  pkg/haproxy/socket/socket.go
  pkg/haproxy/socket/socket_test.go
  pkg/haproxy/utils/utils.go
Labels: v0.14
