Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2021-02, with the labels that each got.

#729 Use field converter to remove port from hdr host
  pkg/haproxy/instance_test.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.11, v0.12, v0.13

#728 Fix path precedence of distinct match types
  docs/content/en/docs/configuration/keys.md
  pkg/haproxy/config.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/maps.go
  pkg/haproxy/types/maps_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.11, v0.12, v0.13

#730 Add sni and verifyhost to secure connections
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.11, v0.12, v0.13

#731 Add support for native redirection of default backend
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/types/global.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.12, v0.13

#726 Update to networking.k8s.io/v1 api
  docs/content/en/docs/configuration/command-line.md
  docs/content/en/docs/configuration/keys.md
  docs/content/en/docs/examples/blue-green.md
  docs/content/en/docs/examples/metrics.md
  docs/content/en/docs/examples/metrics/whoami-ingress.yaml
  docs/content/en/docs/examples/modsecurity.md
  docs/content/en/docs/getting-started/_index.md
  examples/auth/oauth/app.yaml
  examples/blue-green/README.md
  examples/deployment/README.md
  examples/modsecurity/README.md
  examples/multi-tls/ingress-multi-tls.yaml
  examples/tls-termination/ingress-tls-default.yaml
  examples/tls-termination/ingress-tls-foobar.yaml
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/common/ingress/controller/status.go
  pkg/common/ingress/types.go
  pkg/controller/cache.go
  pkg/controller/controller.go
  pkg/controller/listers.go
  pkg/converters/helper_test/cachemock.go
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/converters/types/interfaces.go
Labels: v0.13

#736 Fix shrinking of prioritized paths
  pkg/haproxy/types/maps.go
  pkg/haproxy/types/maps_test.go
Labels: v0.11, v0.12, v0.13

#743 Improve crt validation with ssl_c_verify
  pkg/haproxy/instance_test.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.10, v0.11, v0.12, v0.13, v0.8, v0.9

#739 Read the whole input when the response fills the buffer
  pkg/haproxy/instance.go
  pkg/haproxy/utils/utils.go
  pkg/haproxy/utils/utils_test.go
Labels: v0.12, v0.13

#740 Remove unix socket before start acme server
  pkg/acme/server.go
Labels: v0.12, v0.13

#742 Fix initial weight configuration
  pkg/converters/ingress/ingress.go
Labels: v0.10, v0.11, v0.12, v0.13, v0.8, v0.9
