Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2022-04, with the labels that each got.

#914 Only inspect SSL handshake for SNI routing for SSL passthrough, fixes #912
  pkg/haproxy/instance_test.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.13, v0.14

#911 Add ssl-fingerprint-sha2-bits configuration key
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.14

#915 Add http-response configuration keys
  docs/content/en/docs/configuration/keys.md
  pkg/common/ingress/controller/launch.go
  pkg/common/ingress/types.go
  pkg/converters/ingress/annotations/global.go
  pkg/converters/ingress/annotations/global_test.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/annotations/updater_test.go
  pkg/converters/ingress/types/global.go
  pkg/haproxy/instance.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/lua/services.lua
  rootfs/etc/templates/haproxy/haproxy.tmpl
  rootfs/etc/templates/responses/response.http.tmpl
  rootfs/etc/templates/responses/responses.lua.tmpl
Labels: v0.14

#916 Fix reload failure detection on 2.5+
  pkg/haproxy/instance.go
Labels: v0.12, v0.13, v0.14
