Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2022-08, with the labels that each got.

#942 Fix go lint issues
  .golangci.yml
  pkg/acme/client_test.go
  pkg/controller/cache.go
  pkg/converters/ingress/ingress.go
  pkg/haproxy/dynupdate.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/socket/socket.go
  pkg/haproxy/template/template.go
  pkg/haproxy/template/template_test.go
Labels: v0.14

#941 Add apk upgrade on container building
  builder/Dockerfile
  rootfs/Dockerfile
Labels: v0.10, v0.12, v0.13, v0.14

#943 Update client-go from v0.23.8 to v0.23.9 and indirect dependencies
  go.mod
  go.sum
Labels: v0.13, v0.14

#945 Migrate to new versions / off deprecated packages.
  go.mod
  go.sum
  pkg/common/ingress/controller/status.go
  pkg/haproxy/template/funcmap.go
Labels: v0.14, v0.15
