Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2023-05, with the labels that each got.

#959 Adds support for EndpointSlices API in master
  .golangci.yml
  docs/content/en/docs/configuration/command-line.md
  pkg/common/ingress/controller/controller.go
  pkg/common/ingress/controller/launch.go
  pkg/controller/legacy/cache.go
  pkg/controller/legacy/controller.go
  pkg/controller/legacy/listers.go
  pkg/controller/services/cache.go
  pkg/converters/configmap/tcpservices.go
  pkg/converters/configmap/tcpservices_test.go
  pkg/converters/gateway/gateway.go
  pkg/converters/gateway/gateway_test.go
  pkg/converters/helper_test/cachemock.go
  pkg/converters/helper_test/k8sobjects.go
  pkg/converters/ingress/ingress.go
  pkg/converters/ingress/ingress_test.go
  pkg/converters/types/interfaces.go
  pkg/converters/types/options.go
  pkg/converters/utils/services.go
  pkg/converters/utils/services_test.go
Labels: v0.14, v0.15

#1002 Fix gw-v1alpha2 delete notifications
  pkg/controller/cache.go
Labels: v0.14

#995 Skip acme-challenge path on to/from redirects
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/types/global.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.14, v0.15

#1001 Fixes configmap based tcp sync
  pkg/converters/converters.go
Labels: v0.13, v0.14, v0.15

#1003 Ensure predictable tcp by sorting endpoints
  pkg/haproxy/types/tcpbackend.go
Labels: v0.10, v0.12, v0.13, v0.14, v0.15

#1004 Change owner of crt/key files to haproxy pid
  pkg/common/net/ssl/ssl.go
Labels: v0.12, v0.13, v0.14, v0.15
