Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2023-07, with the labels that each got.

#1006 Update dependencies
  .github/workflows/build.yaml
  builder/Dockerfile
  go.mod
  go.sum
  rootfs/Dockerfile
Labels: v0.15

#1009 fix: config-backend annotation also for TCP-Backends
  pkg/haproxy/instance_test.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
Labels: v0.14, v0.15

#986 Prefer ingressClassName over annotations in docs
  docs/content/en/docs/examples/metrics.md
  docs/content/en/docs/getting-started/_index.md
Labels: v0.14, v0.15

#1010 Redirect hosts only to domains with associated backends
  pkg/converters/ingress/annotations/host.go
  pkg/converters/ingress/annotations/host_test.go
Labels: v0.13, v0.14, v0.15

#1011 Create endpoints on a predictable order
  pkg/converters/utils/services.go
  pkg/converters/utils/services_test.go
  pkg/haproxy/types/tcpbackend.go
Labels: v0.10, v0.12, v0.13, v0.14, v0.15

#1012 Remove generation predicate on endpoints
  pkg/controller/reconciler/watchers.go
Labels: v0.15

#1013 Add endpointslice api on v0.15 handler
  pkg/common/ingress/controller/launch.go
  pkg/controller/config/config.go
  pkg/controller/reconciler/watchers.go
  pkg/controller/services/services.go
Labels: v0.15

#1015 Fix shard render when the last backend is removed
  pkg/haproxy/config.go
  pkg/haproxy/types/backends.go
Labels: v0.12, v0.13, v0.14, v0.15

#1016 Add wildcard as a valid cors allowed header
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/validator.go
Labels: v0.10, v0.12, v0.13, v0.14, v0.15
