Repository jcmoraisjr/haproxy-ingress, pull requests merged in 2024-06, with the labels that each got.

#1117 Ensure https redirect happens before root redirect
  pkg/converters/ingress/annotations/global.go
  pkg/haproxy/config.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/host.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
  tests/framework/options/objects.go
  tests/integration/integration_test.go
Labels: v0.12, v0.13, v0.14, v0.15

#1119 Allows secure backend configuration from global
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/backend_test.go
  pkg/converters/ingress/annotations/mapper.go
Labels: v0.12, v0.13, v0.14, v0.15

#1118 Add ssl-always-follow-redirect option
  docs/content/en/docs/configuration/keys.md
  pkg/converters/ingress/annotations/backend.go
  pkg/converters/ingress/annotations/updater.go
  pkg/converters/ingress/annotations/updater_test.go
  pkg/converters/ingress/defaults.go
  pkg/converters/ingress/types/annotations.go
  pkg/haproxy/types/host.go
  pkg/haproxy/types/types.go
  tests/framework/framework.go
  tests/integration/integration_test.go
Labels: v0.14, v0.15

#1132 Add TLS related integration tests
  tests/framework/framework.go
  tests/framework/options/certificates.go
  tests/framework/options/objects.go
  tests/framework/options/request.go
  tests/framework/ssl.go
  tests/framework/utils.go
  tests/integration/integration_test.go
Labels: v0.15

#1137 Upgrade golang from 1.22.2 to 1.22.4
  .github/workflows/build.yaml
  builder/Dockerfile
  go.mod
Labels: v0.15

#1139 Upgrade embedded haproxy from 2.6.16 to 2.6.17
  builder/Dockerfile
  rootfs/Dockerfile
Labels: v0.15

#1134 Change default master-worker config to true
  docs/content/en/docs/configuration/command-line.md
  pkg/controller/config/options.go
Labels: v0.15

#1135 Local building improvements
  Makefile
  README.md
  pkg/controller/services/svcleader.go
  pkg/controller/services/svcstatusing.go
Labels: v0.14, v0.15

#1138 doc: add haproxy logging to stdout
  docs/content/en/docs/configuration/keys.md
Labels: v0.12, v0.13, v0.14, v0.15

#1136 Move embedded haproxy process to a distinct pid group
  builder/Dockerfile
  pkg/haproxy/instance.go
  rootfs/Dockerfile
Labels: v0.14, v0.15

#1144 doc: add a light weight version of haproxy ingress logo
  docs/assets/icons/logo-bold.svg
  docs/assets/icons/logo.odg
  docs/assets/icons/logo.svg
Labels: v0.15

#1133 Remove dedicated maps for SNI match
  pkg/haproxy/config.go
  pkg/haproxy/instance_test.go
  pkg/haproxy/types/types.go
  rootfs/etc/templates/haproxy/haproxy.tmpl
  tests/integration/integration_test.go
Labels: v0.14, v0.15
